# Generated by Django 4.1.6 on 2023-02-02 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit', models.CharField(max_length=50, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commints', to='test3.post')),
            ],
        ),
    ]
